## Data dingoes                                                           *
#* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#libraries
library(shinydashboard)
#header
header <- dashboardHeader(
  title = "Big decisions"
)
#sidebar navigation
sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Dashboard", tabName="dashboard", icon = icon("tachometer")),
    # menuItem("Data", tabName="data", icon = icon("table")),
    menuItem("About", tabName="about", icon = icon("info"))
  )
)
#body
body <- dashboardBody(
  tags$head(
    tags$link(rel = "stylesheet", type = "text/css", href = "custom.css")
  ),
  tabItems(
    tabItem(tabName ="dashboard",
            # h3("About me"),
            fluidRow(
              column(width = 12,
                     box(title='About me', solidHeader=TRUE,
                         status = 'primary',
                         # background = "blue",
                         width = NULL,
                         collapsible = TRUE,
                         selectInput("occupation", "My occupation",
                                     selected = '1351',
                                     c('Livestock farmers 1213' = '1213',
                                       'Advertising and sales managers 1311' = '1311',
                                       'Corporate services managers 1321' = '1321',
                                       'Finance managers 1322' = '1322',
                                       'Human resource managers 1323' = '1323',
                                       'Policy and planning managers 1324' = '1324',
                                       'Research and development managers 1325' = '1325',
                                       'Construction managers 1331' = '1331',
                                       'Engineering managers 1332' = '1332',
                                       'Importers, exporters and wholesalers 1333' = '1333',
                                       'Manufacturers 1334' = '1334',
                                       'Production managers 1335' = '1335',
                                       'Supply and distribution managers 1336' = '1336',
                                       'Child care centre managers 1341' = '1341',
                                       'Health and welfare services managers 1342' = '1342',
                                       'School principals 1343' = '1343',
                                       'Other education managers 1344' = '1344',
                                       'ICT managers 1351' = '1351',
                                       'Commissioned officers (management) 1391' = '1391',
                                       'Senior non-commissioned defence force members 1392' = '1392',
                                       'Other specialist managers 1399' = '1399',
                                       'Cafe and restaurant managers 1411' = '1411',
                                       'Caravan park and camping ground managers 1412' = '1412',
                                       'Hotel and motel managers 1413' = '1413',
                                       'Licensed club managers 1414' = '1414',
                                       'Other accommodation and hospitality managers 1419' = '1419',
                                       'Retail managers 1421' = '1421',
                                       'Amusement, fitness and sports centre managers 1491' = '1491',
                                       'Call or contact centre and customer service managers 1492' = '1492',
                                       'Conference and event organisers 1493' = '1493',
                                       'Transport services managers 1494' = '1494',
                                       'Other hospitality, retail and service managers 1499' = '1499',
                                       'Actors, dancers and other entertainers 2111' = '2111',
                                       'Music professionals 2112' = '2112',
                                       'Photographers 2113' = '2113',
                                       'Visual arts and crafts professionals 2114' = '2114',
                                       'Artistic directors, and media producers and presenters 2121' = '2121',
                                       'Authors, and book and script editors 2122' = '2122',
                                       'Film, television, radio and stage directors 2123' = '2123',
                                       'Journalists and other writers 2124' = '2124',
                                       'Accountants 2211' = '2211',
                                       'Auditors, company secretaries and corporate treasurers 2212' = '2212',
                                       'Financial brokers 2221' = '2221',
                                       'Financial dealers 2222' = '2222',
                                       'Financial investment advisers and managers 2223' = '2223',
                                       'Human resource professionals 2231' = '2231',
                                       'ICT trainers 2232' = '2232',
                                       'Training and development professionals 2233' = '2233',
                                       'Actuaries, mathematicians and statisticians 2241' = '2241',
                                       'Archivists, curators and records managers 2242' = '2242',
                                       'Economists 2243' = '2243',
                                       'Intelligence and policy analysts 2244' = '2244',
                                       'Land economists and valuers 2245' = '2245',
                                       'Librarians 2246' = '2246',
                                       'Management and organisation analysts 2247' = '2247',
                                       'Other information and organisation professionals 2249' = '2249',
                                       'Advertising and marketing professionals 2251' = '2251',
                                       'ICT sales professionals 2252' = '2252',
                                       'Public relations professionals 2253' = '2253',
                                       'Technical sales representatives 2254' = '2254',
                                       'Air transport professionals 2311' = '2311',
                                       'Marine transport professionals 2312' = '2312',
                                       'Architects and landscape architects 2321' = '2321',
                                       'Cartographers and surveyors 2322' = '2322',
                                       'Fashion, industrial and jewellery designers 2323' = '2323',
                                       'Graphic and web designers, and illustrators 2324' = '2324',
                                       'Interior designers 2325' = '2325',
                                       'Urban and regional planners 2326' = '2326',
                                       'Chemical and materials engineers 2331' = '2331',
                                       'Civil engineering professionals 2332' = '2332',
                                       'Electrical engineers 2333' = '2333',
                                       'Electronics engineers 2334' = '2334',
                                       'Industrial, mechanical and production engineers 2335' = '2335',
                                       'Mining engineers 2336' = '2336',
                                       'Other engineering professionals 2339' = '2339',
                                       'Agricultural and forestry scientists 2341' = '2341',
                                       'Chemists, and food and wine scientists 2342' = '2342',
                                       'Environmental scientists 2343' = '2343',
                                       'Geologists and geophysicists 2344' = '2344',
                                       'Life scientists 2345' = '2345',
                                       'Medical laboratory scientists 2346' = '2346',
                                       'Veterinarians 2347' = '2347',
                                       'Other natural and physical science professionals 2349' = '2349',
                                       'Early childhood (pre-primary school) teachers 2411' = '2411',
                                       'Primary school teachers 2412' = '2412',
                                       'Middle school teachers 2413' = '2413',
                                       'Secondary school teachers 2414' = '2414',
                                       'Special education teachers 2415' = '2415',
                                       'University lecturers and tutors 2421' = '2421',
                                       'Vocational education teachers 2422' = '2422',
                                       'Education advisers and reviewers 2491' = '2491',
                                       'Private tutors and teachers 2492' = '2492',
                                       'Teachers of English to speakers of other languages 2493' = '2493',
                                       'Dieticians 2511' = '2511',
                                       'Medical imaging professionals 2512' = '2512',
                                       'Occupational and environmental health professionals 2513' = '2513',
                                       'Optometrists and orthoptists 2514' = '2514',
                                       'Pharmacists 2515' = '2515',
                                       'Other health diagnostic and promotion professionals 2519' = '2519',
                                       'Chiropractors and osteopaths 2521' = '2521',
                                       'Complementary health therapists 2522' = '2522',
                                       'Dental practitioners 2523' = '2523',
                                       'Occupational therapists 2524' = '2524',
                                       'Physiotherapists 2525' = '2525',
                                       'Podiatrists 2526' = '2526',
                                       'Speech professionals and audiologists 2527' = '2527',
                                       'Generalist medical practitioners 2531' = '2531',
                                       'Anaesthetists 2532' = '2532',
                                       'Internal medicine specialists 2533' = '2533',
                                       'Psychiatrists 2534' = '2534',
                                       'Surgeons 2535' = '2535',
                                       'Other medical practitioners 2539' = '2539',
                                       'Midwives 2541' = '2541',
                                       'Nurse educators and researchers 2542' = '2542',
                                       'Nurse managers 2543' = '2543',
                                       'Registered nurses 2544' = '2544',
                                       'ICT business and systems analysts 2611' = '2611',
                                       'Multimedia specialists and web developers 2612' = '2612',
                                       'Software and applications programmers 2613' = '2613',
                                       'Database and systems administrators, and ICT security specialists 2621' = '2621',
                                       'Computer network professionals 2631' = '2631',
                                       'ICT support and test engineers 2632' = '2632',
                                       'Telecommunications engineering professionals 2633' = '2633',
                                       'Barristers 2711' = '2711',
                                       'Judicial and other legal professionals 2712' = '2712',
                                       'Solicitors 2713' = '2713',
                                       'Counsellors 2721' = '2721',
                                       'Ministers of religion 2722' = '2722',
                                       'Psychologists 2723' = '2723',
                                       'Social professionals 2724' = '2724',
                                       'Social workers 2725' = '2725',
                                       'Welfare, recreation and community arts workers 2726' = '2726',
                                       'Agricultural technicians 3111' = '3111',
                                       'Medical technicians 3112' = '3112',
                                       'Primary products inspectors 3113' = '3113',
                                       'Science technicians 3114' = '3114',
                                       'Architectural, building and surveying technicians 3121' = '3121',
                                       'Civil engineering draftspersons and technicians 3122' = '3122',
                                       'Electrical engineering draftspersons and technicians 3123' = '3123',
                                       'Electronic engineering draftspersons and technicians 3124' = '3124',
                                       'Mechanical engineering draftspersons and technicians 3125' = '3125',
                                       'Safety inspectors 3126' = '3126',
                                       'Other building and engineering technicians 3129' = '3129',
                                       'ICT support technicians 3131' = '3131',
                                       'Telecommunications technical specialists 3132' = '3132',
                                       'Automotive electricians 3211' = '3211',
                                       'Motor mechanics 3212' = '3212',
                                       'Metal casting, forging and finishing trades workers 3221' = '3221',
                                       'Sheetmetal trades workers 3222' = '3222',
                                       'Structural steel and welding trades workers 3223' = '3223',
                                       'Aircraft maintenance engineers 3231' = '3231',
                                       'Metal fitters and machinists 3232' = '3232',
                                       'Precision metal trades workers 3233' = '3233',
                                       'Toolmakers and engineering patternmakers 3234' = '3234',
                                       'Panelbeaters 3241' = '3241',
                                       'Vehicle body builders and trimmers 3242' = '3242',
                                       'Vehicle painters 3243' = '3243',
                                       'Bricklayers and stonemasons 3311' = '3311',
                                       'Carpenters and joiners 3312' = '3312',
                                       'Floor finishers 3321' = '3321',
                                       'Painting trades workers 3322' = '3322',
                                       'Glaziers 3331' = '3331',
                                       'Plasterers 3332' = '3332',
                                       'Roof tilers 3333' = '3333',
                                       'Wall and floor tilers 3334' = '3334',
                                       'Plumbers 3341' = '3341',
                                       'Electricians 3411' = '3411',
                                       'Airconditioning and refrigeration mechanics 3421' = '3421',
                                       'Electrical distribution trades workers 3422' = '3422',
                                       'Electronics trades workers 3423' = '3423',
                                       'Telecommunications trades workers 3424' = '3424',
                                       'Bakers and pastrycooks 3511' = '3511',
                                       'Butchers and smallgoods makers 3512' = '3512',
                                       'Chefs 3513' = '3513',
                                       'Cooks 3514' = '3514',
                                       'Animal attendants and trainers 3611' = '3611',
                                       'Shearers 3612' = '3612',
                                       'Veterinary nurses 3613' = '3613',
                                       'Florists 3621' = '3621',
                                       'Gardeners 3622' = '3622',
                                       'Greenkeepers 3623' = '3623',
                                       'Nurserypersons 3624' = '3624',
                                       'Hairdressers 3911' = '3911',
                                       'Binders, finishers and screen printers 3921' = '3921',
                                       'Graphic pre-press trades workers 3922' = '3922',
                                       'Printers 3923' = '3923',
                                       'Clothing trades workers 3932' = '3932',
                                       'Upholsterers 3933' = '3933',
                                       'Cabinetmakers 3941' = '3941',
                                       'Wood machinists and other wood trades workers 3942' = '3942',
                                       'Boat builders and shipwrights 3991' = '3991',
                                       'Chemical, gas, petroleum and power generation plant operators 3992' = '3992',
                                       'Gallery, library and museum technicians 3993' = '3993',
                                       'Jewellers 3994' = '3994',
                                       'Performing arts technicians 3995' = '3995',
                                       'Signwriters 3996' = '3996',
                                       'Other miscellaneous technicians and trades workers 3999' = '3999',
                                       'Ambulance officers and paramedics 4111' = '4111',
                                       'Dental hygienists, technicians and therapists 4112' = '4112',
                                       'Diversional therapists 4113' = '4113',
                                       'Enrolled and mothercraft nurses 4114' = '4114',
                                       'Indigenous health workers 4115' = '4115',
                                       'Massage therapists 4116' = '4116',
                                       'Welfare support workers 4117' = '4117',
                                       'Child carers 4211' = '4211',
                                       'Education aides 4221' = '4221',
                                       'Aged and disabled carers 4231' = '4231',
                                       'Dental assistants 4232' = '4232',
                                       'Nursing support and personal care workers 4233' = '4233',
                                       'Special care workers 4234' = '4234',
                                       'Bar attendants and baristas 4311' = '4311',
                                       'Cafe workers 4312' = '4312',
                                       'Gaming workers 4313' = '4313',
                                       'Hotel service managers 4314' = '4314',
                                       'Waiters 4315' = '4315',
                                       'Other hospitality workers 4319' = '4319',
                                       'Defence force members - other ranks 4411' = '4411',
                                       'Fire and emergency workers 4412' = '4412',
                                       'Police 4413' = '4413',
                                       'Prison officers 4421' = '4421',
                                       'Security officers and guards 4422' = '4422',
                                       'Beauty therapists 4511' = '4511',
                                       'Driving instructors 4512' = '4512',
                                       'Funeral workers 4513' = '4513',
                                       'Gallery, museum and tour guides 4514' = '4514',
                                       'Personal care consultants 4515' = '4515',
                                       'Tourism and travel advisers 4516' = '4516',
                                       'Travel attendants 4517' = '4517',
                                       'Other personal service workers 4518' = '4518',
                                       'Fitness instructors 4521' = '4521',
                                       'Outdoor adventure guides 4522' = '4522',
                                       'Sports coaches, instructors and officials 4523' = '4523',
                                       'Sportspersons 4524' = '4524',
                                       'Contract, program and project administrators 5111' = '5111',
                                       'Office managers 5121' = '5121',
                                       'Practice managers 5122' = '5122',
                                       'Personal assistants 5211' = '5211',
                                       'Secretaries 5212' = '5212',
                                       'General clerks 5311' = '5311',
                                       'Keyboard operators 5321' = '5321',
                                       'Call or contact centre workers 5411' = '5411',
                                       'Inquiry clerks 5412' = '5412',
                                       'Receptionists 5421' = '5421',
                                       'Accounting clerks 5511' = '5511',
                                       'Bookkeepers 5512' = '5512',
                                       'Payroll clerks 5513' = '5513',
                                       'Bank workers 5521' = '5521',
                                       'Credit and loans officers 5522' = '5522',
                                       'Insurance, money market and statistical clerks 5523' = '5523',
                                       'Betting clerks 5611' = '5611',
                                       'Couriers and postal deliverers 5612' = '5612',
                                       'Filing and registry clerks 5613' = '5613',
                                       'Mail sorters 5614' = '5614',
                                       'Survey interviewers 5615' = '5615',
                                       'Switchboard operators 5616' = '5616',
                                       'Other clerical and office support workers 5619' = '5619',
                                       'Purchasing and supply logistics clerks 5911' = '5911',
                                       'Transport and despatch clerks 5912' = '5912',
                                       'Conveyancers and legal executives 5991' = '5991',
                                       'Court and legal clerks 5992' = '5992',
                                       'Debt collectors 5993' = '5993',
                                       'Human resource clerks 5994' = '5994',
                                       'Inspectors and regulatory officers 5995' = '5995',
                                       'Insurance investigators, loss adjusters and risk surveyors 5996' = '5996',
                                       'Library assistants 5997' = '5997',
                                       'Other miscellaneous clerical and administrative workers 5999' = '5999',
                                       'Auctioneers, and stock and station agents 6111' = '6111',
                                       'Insurance agents 6112' = '6112',
                                       'Sales representatives 6113' = '6113',
                                       'Real estate sales agents 6121' = '6121',
                                       'Sales assistants (general) 6211' = '6211',
                                       'ICT sales assistants 6212' = '6212',
                                       'Motor vehicle and vehicle parts salespersons 6213' = '6213',
                                       'Pharmacy sales assistants 6214' = '6214',
                                       'Retail supervisors 6215' = '6215',
                                       'Service station attendants 6216' = '6216',
                                       'Street vendors and related salespersons 6217' = '6217',
                                       'Other sales assistants and salespersons 6219' = '6219',
                                       'Checkout operators and office cashiers 6311' = '6311',
                                       'Models and sales demonstrators 6391' = '6391',
                                       'Retail and wool buyers 6392' = '6392',
                                       'Telemarketers 6393' = '6393',
                                       'Ticket salespersons 6394' = '6394',
                                       'Visual merchandisers 6395' = '6395',
                                       'Other sales support workers 6399' = '6399',
                                       'Clay, concrete, glass and stone processing machine operators 7111' = '7111',
                                       'Industrial spraypainters 7112' = '7112',
                                       'Paper and wood processing machine operators 7113' = '7113',
                                       'Photographic developers and printers 7114' = '7114',
                                       'Plastics and rubber production machine operators 7115' = '7115',
                                       'Sewing machinists 7116' = '7116',
                                       'Textile and footwear production machine operators 7117' = '7117',
                                       'Other machine operators 7119' = '7119',
                                       'Crane, hoist and lift operators 7121' = '7121',
                                       'Drillers, miners and shot firers 7122' = '7122',
                                       'Engineering production systems workers 7123' = '7123',
                                       'Other stationary plant operators 7129' = '7129',
                                       'Agricultural, forestry and horticultural plant operators 7211' = '7211',
                                       'Earthmoving plant operators 7212' = '7212',
                                       'Forklift drivers 7213' = '7213',
                                       'Other mobile plant operators 7219' = '7219',
                                       'Automobile drivers 7311' = '7311',
                                       'Bus and coach drivers 7312' = '7312',
                                       'Train and tram drivers 7313' = '7313',
                                       'Delivery drivers 7321' = '7321',
                                       'Truck drivers 7331' = '7331',
                                       'Storepersons 7411' = '7411',
                                       'Car detailers 8111' = '8111',
                                       'Commercial cleaners 8112' = '8112',
                                       'Domestic cleaners 8113' = '8113',
                                       'Housekeepers 8114' = '8114',
                                       'Laundry workers 8115' = '8115',
                                       'Other cleaners 8116' = '8116',
                                       'Building and plumbing labourers 8211' = '8211',
                                       'Concreters 8212' = '8212',
                                       'Fencers 8213' = '8213',
                                       'Insulation and home improvement installers 8214' = '8214',
                                       'Paving and surfacing labourers 8215' = '8215',
                                       'Railway track workers 8216' = '8216',
                                       'Structural steel construction workers 8217' = '8217',
                                       'Other construction and mining labourers 8219' = '8219',
                                       'Food and drink factory workers 8311' = '8311',
                                       'Meat boners and slicers, and slaughterers 8312' = '8312',
                                       'Meat, poultry and seafood process workers 8313' = '8313',
                                       'Packers 8321' = '8321',
                                       'Product assemblers 8322' = '8322',
                                       'Metal engineering process workers 8391' = '8391',
                                       'Plastics and rubber factory workers 8392' = '8392',
                                       'Product quality controllers 8393' = '8393',
                                       'Timber and wood process workers 8394' = '8394',
                                       'Other factory process workers 8399' = '8399',
                                       'Aquaculture workers 8411' = '8411',
                                       'Crop farm workers 8412' = '8412',
                                       'Forestry and logging workers 8413' = '8413',
                                       'Garden and nursery labourers 8414' = '8414',
                                       'Livestock farm workers 8415' = '8415',
                                       'Mixed crop and livestock farm workers 8416' = '8416',
                                       'Other farm, forestry and garden workers 8419' = '8419',
                                       'Fast food cooks 8511' = '8511',
                                       'Food trades assistants 8512' = '8512',
                                       'Kitchenhands 8513' = '8513',
                                       'Freight and furniture handlers 8911' = '8911',
                                       'Shelf fillers 8912' = '8912',
                                       'Caretakers 8991' = '8991',
                                       'Deck and fishing hands 8992' = '8992',
                                       'Handypersons 8993' = '8993',
                                       'Motor vehicle parts and accessories fitters 8994' = '8994',
                                       'Printing assistants and table workers 8995' = '8995',
                                       'Recycling and rubbish collectors 8996' = '8996',
                                       'Vending machine attendants 8997' = '8997',
                                       'Other miscellaneous labourers 8999' = '8999')),
                         selectInput("age", "My age",
                                     c('20-24' = 1,
                                       '25-29' = 2,
                                       '30-34' = 3)),
                         fluidRow(#begin fluid row
                           column(width = 6,
                                  selectInput("selectFrom", "I currently live in",
                                              selected="SA",
                                              c('Sydney' = 'NSW',
                                                'Melbourne' = 'VIC',
                                                'Brisbane' = 'QLD',
                                                'Adelaide' = 'SA',
                                                'Perth' = 'WA',
                                                'Hobart' = 'TAS',
                                                'Darwin' = 'NT',
                                                'Canberra' = 'ACT'))),
                           column(width = 6,
                                  selectInput("selectTo", "I'm thinking of moving to",
                                              selected="VIC",
                                              c('Sydney' = 'NSW',
                                                'Melbourne' = 'VIC',
                                                'Brisbane' = 'QLD',
                                                'Adelaide' = 'SA',
                                                'Perth' = 'WA',
                                                'Hobart' = 'TAS',
                                                'Darwin' = 'NT',
                                                'Canberra' = 'ACT')))
                         )#end fluid row
                     )
                     
              ), #end of column item
column(width = 12,
       h3("What are my options?")
       ), #end of column item
              column(width = 12,
                     box(title='Average weekly earnings for my occupation',
                         solidHeader=TRUE,
                         background = "blue",
                         width = NULL,
                         collapsible = TRUE,
                         htmlOutput("outWage", inline = FALSE)
                     )), #end of column item
# column(width = 2,
#        br()
# ),
# column(width = 5,
#        h3("Adelaide")
# ), #end of column item
# column(width = 5,
#        h3("Melbourne")
# ), #end of column item
column(width = 1,
       h1(icon("usd"))
), #end of column item
              column(width = 5,
       box(title='Adelaide', solidHeader=F,
           background = "light-blue",
           width = NULL,
           collapsible = TRUE,
           htmlOutput("outDemand2", inline = FALSE)
       )), #end of column item
column(width = 5,
       box(title='Melbourne', solidHeader=F,
           background = "light-blue",
           width = NULL,
           collapsible = TRUE,
           htmlOutput("outDemand1", inline = FALSE)
       )), #end of column item
column(width = 12,
       hr(),
       h4("Cost of housing")),
column(width = 1,
       h1(icon("home"))
), #end of column item
column(width = 5,
       box(title='Adelaide', solidHeader=TRUE,
           background = "green",
           width = NULL,
           collapsible = F,
           htmlOutput("outHousingPrice2", inline = FALSE),
           htmlOutput("outHousing2", inline = FALSE)
       )), #end of column item

column(width = 5,
       box(title='Melbourne', solidHeader=F,
           background = "green",
           width = NULL,
           collapsible = TRUE,
           htmlOutput("outHousingPrice1", inline = FALSE),
           htmlOutput("outHousing1", inline = FALSE)
       )), #end of column item
column(width = 12,
       hr(),
       h4("Cost of public transport")), #end of quality
column(width = 1,
           h1(icon("bus"))
       ), #end of column item
              column(width = 5,
                     box(title='Adelaide', solidHeader=F,
                         background = "orange",
                         width = NULL,
                         collapsible = TRUE,
                         # htmlOutput("outTransit", inline = FALSE),
                         tableOutput("outTransit2")
                     )), #end of column item
column(width = 5,
       box(title='Melbourne', solidHeader=TRUE,
           background = "orange",
           width = NULL,
           collapsible = TRUE,
           # htmlOutput("outTransit", inline = FALSE),
           tableOutput("outTransit1")
       )), #end of column item
column(width = 12,
       hr(),
       h4("Residents belonging to my age group")), #end of quality
column(width = 1,
       h1(icon("users"))
), #end of column item
column(width = 5,
       box(title='Adelaide City', solidHeader=F,
           background = "maroon",
           width = NULL,
           collapsible = TRUE,
           # htmlOutput("outTransit", inline = FALSE),
           htmlOutput("outPop1")
       )), #end of column item
column(width = 5,
       box(title='Melbourne City', solidHeader=TRUE,
           background = "maroon",
           width = NULL,
           collapsible = TRUE,
           # htmlOutput("outTransit", inline = FALSE),
           htmlOutput("outPop2")
       ))
# column(width = 12,
#        box(title='', solidHeader=TRUE,
#            # background = "black",
#            width = NULL,
#            collapsible = TRUE,
#            # htmlOutput("outTransit", inline = FALSE),
#            plotOutput("graphTransit")
#        )) #end of column item
              )),
  ## Data tab
#   tabItem(tabName ="data",
#           h1("Datasets used"),
#           includeHTML("data.txt")
#   ),
  ## Help or about tab
  tabItem(tabName ="about",
          h1("About"),
          includeHTML("about.txt")
  )
  ))

dashboardPage(skin='purple',
  header,
  sidebar,
  body
)